backend:
  name: github
  repo: zachlewton/harrison-smith
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: music
    label: music
    folder: data/music
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: url, label: Url, widget: string }
      - { name: album_art, label: Album Art, widget: image }
  - name: other_work
    label: other work
    folder: data/other_work
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: artist, label: Artist, widget: string }
      - { name: url, label: Url, widget: string }
      - { name: role, label: Role, widget: text }
